const mongoose = require("mongoose");

const appointmentSchema = new mongoose.Schema(
  {
    hospital: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Hospital",
      required: false,
      index: true,
    },

    appointmentId: {
      type: String,
      required: false,
      unique: true,
      sparse: true,
      trim: true,
      // Auto-generated by backend: A-YYYY-000001 (set on create)
    },

    patient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient",
      required: true,
    },

    doctor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Doctor",
      required: true,
    },

    reason: {
      type: String,
      required: true,
      trim: true,
    },

    status: {
      type: String,
      enum: ["Today", "Upcoming", "Completed", "Cancelled"],
      default: "Upcoming",
    },

    type: {
      type: String,
      enum: [
        "hospital",
        "zoom",
        "call",
        "video_call",
        "visit",
        "online",
        "checkup",
        "consultation",
        "emergency",
        "tele-caller",
      ],
      default: "hospital",
    },

    appointmentDateTime: {
      type: Date,
      required: true,
    },

    /** Video consult link (e.g. Google Meet). */
    videoUrl: {
      type: String,
      trim: true,
      maxlength: 2048,
    },

    /** Set when booked from Razorpay flow; avoids duplicate appointments on webhook retry. */
    razorpayPaymentId: {
      type: String,
      trim: true,
      sparse: true,
      unique: true,
      index: true,
    },

    /** PaymentHistory row created on webhook (tele-caller / paid video flow). */
    paymentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PaymentHistory",
      required: false,
      index: true,
    },
  },
  { timestamps: true },
);

appointmentSchema.index({
  hospital: 1,
  patient: 1,
  doctor: 1,
  appointmentDateTime: 1,
});

module.exports = mongoose.model("Appointment", appointmentSchema);
