const mongoose = require("mongoose");

const appointmentSchema = new mongoose.Schema(
  {
    hospital: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Hospital",
      required: false,
      index: true,
    },

    appointmentId: {
      type: String,
      required: false,
      unique: true,
      sparse: true,
      trim: true,
      // Auto-generated by backend: A-YYYY-000001 (set on create)
    },

    patient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient",
      required: true,
    },

    doctor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Doctor",
      required: true,
    },

    reason: {
      type: String,
      required: true,
      trim: true,
    },

    status: {
      type: String,
      enum: ["Today", "Upcoming", "Completed", "Cancelled"],
      default: "Upcoming",
    },

    type: {
      type: String,
      enum: [
        "hospital",
        "zoom",
        "call",
        "visit",
        "online",
        "checkup",
        "consultation",
        "emergency",
      ],
      default: "hospital",
    },

    appointmentDateTime: {
      type: Date,
      required: true,
    },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Appointment", appointmentSchema);
